### PR TITLE
feat: mainnet deployments

### PR DESCRIPTION
**Pull request by floatcoder**
Trying to replicate a Sushiswap deployment can be a bit tricky as it is highly dependent on the compiler version to get the correct bytecode & hence the right pair calculation.

The existing mainnet deployments in the repo (and in the @sushiswap/core npm package) are missing / incorrect.

For instance @FloatProtocol it'd be much nicer to use it direct as part of our Twap oracle tests, rather than having to package these alongside.
```
// The ideal.
import SushiswapFactory from "@sushiswap/core/deployments/mainnet/UniswapV2Factory.json";
// The hack.
import SushiswapRouter from "../utils/contracts/UniswapV2Router02.json";

...

  const Factory = new ContractFactory(
    SushiswapFactory.abi,
    SushiswapFactory.bytecode
  );
  const Router = new ContractFactory(
    SushiswapRouter.abi,
    SushiswapRouter.bytecode
  );

```

### CODE REVIEW

**Comment by matthewlilley** [comment]
> Trying to replicate a Sushiswap deployment can be a bit tricky as it is highly dependent on the compiler version to get the correct bytecode & hence the right pair calculation.
> 
> The existing mainnet deployments in the repo (and in the @sushiswap/core npm package) are missing / incorrect.
> 
> For instance @FloatProtocol it'd be much nicer to use it direct as part of our Twap oracle tests, rather than having to package these alongside.
> 
> ```
> // The ideal.
> import SushiswapFactory from "@sushiswap/core/deployments/mainnet/UniswapV2Factory.json";
> // The hack.
> import SushiswapRouter from "../utils/contracts/UniswapV2Router02.json";
> 
> ...
> 
>   const Factory = new ContractFactory(
>     SushiswapFactory.abi,
>     SushiswapFactory.bytecode
>   );
>   const Router = new ContractFactory(
>     SushiswapRouter.abi,
>     SushiswapRouter.bytecode
>   );
> ```

Ah yes! I manually added the mainnet deployment JSON for the Factory but must've forgotten about the Router. I'll get it added.

**Comment by matthewlilley** [comment]
@floatcoder can you check if @sushiswap/core@2.0.0-canary.1 has everything you need and is correct?

**Comment by floatcoder** [comment]
Not quite!

Big issue is that the `UniswapV2Router` bytecode has the constructor arguments appended to it:

Screenshot from 2021-06-26 11-48-41

So the init hash is off / adding liquidity will always fail.

**Comment by floatcoder** [comment]
Also:
- `deployments/mainnet/UniswapV2Router.json` -> `deployments/mainnet/UniswapV2Router02.json` if you're trying to keep it matching with the other deployments / what would happen if you deployed with hardhat.
- The address of the `UniswapV2Factory.json` is also wrong - should be 0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac although that isn't an issue for replication.

**Comment by matthewlilley** [comment]
Thanks for the DD @floatcoder, LGTM

**Pull request merged**
