### PR TITLE
fix hardhat test and dependency issues

### PR DESCRIPTION
**Pull request by sambacha**
### use `npx` for running hardhat

added the `npx` command before hardhat https://github.com/sushiswap/sushiswap/blob/913076f9c02b8f3bc0d2dfefb59853d86d6e9e17/package.json#L52

Is now:

```json
"test": "npx hardhat test --logs"
```

Per hardhat documentation:

> Out of best practice, Hardhat projects use a local installation of the NPM package hardhat to make  
> sure everyone working on the project is using the same version. This is why you need to use npx or  
> npm scripts to run Hardhat.

[hardhat.org/guides/shorthand.html#context](https://hardhat.org/guides/shorthand.html#context)

### fix npm dependency pathname

- resolve the dependency @boringcrypto/boring-solidity with the FQDN by prefixing it with `git+https://github.com/...`

```bash
    "@boringcrypto/boring-solidity": "git+https://github.com/boringcrypto/BoringSolidity#e06e943",
```

### hardhat/tracer

Enables you to see emitted events when running tests.

```bash
npx hardhat test --logs
```

### resolve lint issue

> fix missing devDependency (solhint)

https://github.com/sushiswap/sushiswap/blob/913076f9c02b8f3bc0d2dfefb59853d86d6e9e17/package.json#L56

> fix solhint configuration

> fixes solhint to work with prettier / prettier-solidity

### additional notes

I did not add the `npx` prefix to any other command's as I do not know if there is a use case for not using them internally (perhaps you use `hh` etc).

Would like to add a workflow for running slither now that I see mythx is being used as well. 

Cheers,

Sam

### CODE REVIEW

**Comment by Clearwood** [comment]
A workflow for Slither would be awesome.
We are using yarn and there should not be any different from using the FQDN or not, right?
Why do you do the prefix with npx?

**Comment by sambacha** [comment]
Appears a transitory issue, either way it's resolved, I did update the dependency to the latest commit for @boringcrypto/boring-solidity and running 

```bash
$ yarn add -D 'boringcrypto/BoringSolidity#b85f13c8f048136b3d3cb7e498ad6b76da05f98c' 
``` 

works now. May be an issue with my local cache that caused the initial issue. 


- Slither Workflow: 
	contains a bash script within the config as well to inform how many errors / warnings / etc are generated. Note that its quite verbose, should probably ignore uniswapV2/ and openzeppelin/ etc. It's generated output is stored as an artifact within GitHub, so you will have to download it to see specifics. [see slither artifact in reference testing branch](https://github.com/sambacha/sushiswap/actions/runs/611022131). 

- Mythx is now separated into its own workflow so that non-contract changes to the repo won't trigger a failing CI build. 

- Added Cache optimizations and `id` tags for the sushiswap/nodejs workflow, it should be easier to view coverage outputs.

**Comment by sambacha** [comment]
Further investigation on usage of mapping a dependency to a `uri` finds:


Git | git@github.com:foo/bar.git | Downloads a public package from a Git repository
-- | -- | --
GitHub | github:foo/bar | Downloads a public package from GitHub

**Review by Clearwood — APPROVED** [review]

**Comment by Clearwood** [comment]
Thanks again

**Pull request merged**
